name: delete comments from open-collective-bot
on:
  workflow_dispatch:
jobs:
  delete-comments:
    runs-on: ubuntu-latest
    steps:
      - uses: izhangzhihao/delete-comment@v0.0.1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: open-collective-bot[bot]
